### ISSUE TITLE
Panic when adding route via web interface

### ISSUE THREAD

**Issue by replay** [grafana/carbon-relay-ng#420]
Version: `master`

How to reproduce:

1) Start carbon-relay-ng with config `examples/carbon-relay-ng.ini`
2) Go to web interface
3) Fill all form fields with following values:
  Route Key: `test`
  Route Type: `sendAllMatch`
  Match prefix: `a`
  Match substring: `b`
  Match regex: `c`
  Address: `127.0.0.1:1234`
4) Click the `Add` button
5) Panic:
```
panic: non-positive interval for NewTicker                                                                                                                                          goroutine 258 [running]:                                                                  time.NewTicker(0x0, 0x40c396)                                                                     /usr/local/go/src/time/tick.go:23 +0x147                                          github.com/grafana/carbon-relay-ng/nsqd.(*DiskQueue).ioLoop(0xc000148360)                         /home/replay/go/src/github.com/grafana/carbon-relay-ng/nsqd/diskqueue.go:540 +0x47created by github.com/grafana/carbon-relay-ng/nsqd.NewDiskQueue                                   /home/replay/go/src/github.com/grafana/carbon-relay-ng/nsqd/diskqueue.go:93 +0x2fb
```

**Comment by je1lylee** [comment]
+1

**Comment by replay** [comment]
@je1lylee The web interface is beta, if you would like to use carbon-relay-ng in a production environment it is recommended to use config files.

**Comment by je1lylee** [comment]
Thank you! I edited config files manually, everything looks good now.
